### ISSUE TITLE
strange auto logout | session kick = back in login screen [ubuntu bionic]

### ISSUE THREAD

**Issue by githubber-spec** [netblue30/fdns#23]
within a virtual machine i often like 10-30% get a kick out of the login session of ubuntu bionic and im back in the login screen. appeared most of the times when there was a issue with the internet connection.  

never reaches the point of ssl connection opened  before being kicked or the filters

so dont reaches the point of 
fdns starting
connecting to adguard server
listening on 127.1.1.1

a few more providers would be nice, at all a nice project

**Comment by netblue30** [comment]
Thanks for reporting it. The fix is in git.

I was able to reproduce it on a real machine. It happens if there is poor or no network connectivity, and the proxy fails to connect to the provider's server. fnds ends up killing X11 - the ugliest bug I've seen in ages! So it will kick you out and bring you to the login screen (X11 runs as regular user, so you can kill it like any other program).

> a few more providers would be nice, at all a nice project

Thanks. 12 providers in the first release several weeks ago, 34 in this moment. The number is going up fast.
